### ISSUE TITLE
Possibility to put max amount of blocks found before payment

### ISSUE THREAD

**Issue by sennevb** [z-classic/z-nomp#113]
If you find multiple blocks, with a bit of time between them.
And for example 3th block is not paid and 4th is allready found, funds are held in the pool till all funds are there..

Is there an option to prevent this and put maximum of blocks in a config file? and then payment is made whatsoever???

i'm losing miners because they think i'm not paying...

**Comment by sonicdx10** [comment]
As an investor and promoter of this type of technology, it is inadmissible to ignore this type of problem (is it?), Since what is intended is, to gain more public giving them security and certainty. We can not take the liberty of not complying with the specific payments according to the policies of the 100 confirmations (we would be falling into advertising fraud). On the other hand, the users wants to receive without problem their remuneration for the time-equipment invested & the energy used. 

This lies in the heart of zcash or of nomp?

But let's not forget ourselves, those who have server, certificates, equipment invested, energy waste. We also occupy the certainty of starting a project and grant such security to the user or customer, why otherwise, I agree with the sennevb, all that is achieved is to lose customers.

**Comment by sonicdx10** [comment]
Payments are working just fine @sennevb

**Comment by sennevb** [comment]
erhmm, how do you mean?? i'm the only one having this problem??
