### ISSUE TITLE
HELP - UNAUTHORIZEET

### ISSUE THREAD

**Issue by isaev8871** [z-classic/z-nomp#182]
Hi! please help who know, in nomp, Unauthorizet t.........x - its many and i think its Overload the server, HOW its STOP!!!! please help
 
i know thats zn adress need, and whrite it everywhere. But any .......people  connect whith t....

**Comment by madbuda** [comment]
please provide some details and logs of what the problem is

**Comment by isaev8871** [comment]
pool work, but some people ithink try connect whith t... adresss and other words

**Comment by isaev8871** [comment]
Unauthorizet t.........x
 Unauthorizet t.........x
 Unauthorizet t.........x
 Unauthorizet monuy.x

**Comment by isaev8871** [comment]
spam

**Comment by isaev8871** [comment]
Unauthorizet t.........x monya:x

**Comment by isaev8871** [comment]
where log copy for you?

**Comment by madbuda** [comment]
if you are using pm2 it will be in ~/.pm2/logs/init.out.log otherwise it should be displayed on the screen.

Unauthorized sounds like a bad miner, I usually just block their IP in the firewall. some older miners try to use an unsupported function to authenticate to a pool `mining.extranonce.subscribe` is the unsupported function

**Comment by isaev8871** [comment]
thanks! block ip's him by ufw)
